export const SET_LOADING = 'SET_LOADING';

/* STOCK ALERT */
export const STOCK_ALERT = 'STOCK_ALERT';
export const STOCK_ALERT_ERROR = 'STOCK_ALERT_ERROR';

/* CONTACT US */
export const CONTACT_US = 'CONTACT_US';
export const CONTACT_US_ERROR = 'CONTACT_US_ERROR';
export const SEND_REPLY = 'SEND_REPLY';
export const SEND_REPLY_ERROR = 'SEND_REPLY_ERROR';

/* LOGIN */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_ERRORS';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const CLEAR_LOGIN_MESSAGE = 'CLEAR_MESSAGE';
export const DELETE_CONTACT_US = 'DELETE_CONTACT_US';
export const DELETE_CONTACT_US_ERROR = 'DELETE_CONTACT_US_ERROR';

// User (teacher/principal) Login
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const CLEAR_USER_LOGIN_ERRORS = 'CLEAR_USER_LOGIN_ERRORS';
export const SET_USER_LOGIN_LOADING = 'SET_USER_LOGIN_LOADING';
export const CLEAR_USER_LOGIN_MESSAGE = 'CLEAR_USER_LOGIN_MESSAGE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_PASSWORD_ERROR = 'CHANGE_USER_PASSWORD_ERROR';

// Change Password Request
export const FORGET_REQUEST = 'FORGET_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';
export const CHANGE_IMAGE_ERROR = 'CHANGE_IMAGE_ERROR';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_ADMIN_ERROR = 'UPDATE_ADMIN_ERROR';

/* CUSTOMIZER */
export const WATCH_CUSTOMIZER = 'WATCH_CUSTOMIZER';
export const ADD_COSTOMIZER = 'ADD_COSTOMIZER';
export const ADD_LAYOUT = 'ADD_LAYOUT';
export const ADD_SIDEBAR_TYPES = 'ADD_SIDEBAR_TYPES';
export const ADD_SIDEBAR_SETTINGS = 'ADD_SIDEBAR_SETTINGS';
export const ADD_COLOR = 'ADD_COLOR';
export const ADD_MIX_BACKGROUND_LAYOUT = 'ADD_MIX_BACKGROUND_LAYOUT';
export const ROUTER_ANIMATION = 'ROUTER_ANIMATION';
export const CHANGE_DARK_MODE = 'CHANGE_DARK_MODE';

/* PRODUCT */
export const PRODUCT_LOADED = 'PRODUCT_LOADED';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const TYPES_LOADED = 'TYPES_LOADED';
export const TYPES_ERROR = 'TYPES_ERROR';
export const ADD_MAKE = 'ADD_MAKE';
export const FILTER_MAKE = 'FILTER_MAKE';
export const DELETE_MAKE = 'DELETE_MAKE';
export const MAKES_LOADED = 'MAKES_LOADED';
export const MAKES_ERROR = 'MAKES_ERROR';
export const ADD_MODEL = 'ADD_MODEL';
export const FILTER_MODEL = 'FILTER_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';
export const MODEL_LOADED = 'MODEL_LOADED';
export const MODEL_ERROR = 'MODEL_ERROR';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_LOADED = 'CATEGORY_LOADED';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const FILTER_SUB_CATEGORY = 'FILTER_SUB_CATEGORY';
export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY';
export const SUBCATEGORY_LOADED = 'SUBCATEGORY_LOADED';
export const SUBCATEGORY_ERROR = 'SUBCATEGORY_ERROR';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';
export const CLEAR_FILE = 'CLEAR_FILE';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';
export const UPDATE_MAKE = 'UPDATE_MAKE';
export const UPDATE_MODEL = 'UPDATE_MODEL';

export const CLEAR_FILTER = 'CLEAR_FILTER';

/* PURCAHSE */
export const PURCHASE_LOADED = 'PURCHASE_LOADED';
export const NEW_PURCHASE = 'NEW_PURCHASE';
export const OLD_PURCHASE = 'OLD_PURCHASE';
export const UPDATE_PURCHASE = 'UPDATE_PURCHASE';
export const UPDATE_OLD_PURCHASE = 'UPDATE_OLD_PURCHASE';
export const RETURN_PURCHASE = 'RETURN_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const PURCHASE_ERROR = 'PURCHASE_ERROR';
// export const FILTER_PURCHASE = 'FILTER_PURCHASE';
export const PURCHASE_RETURN_LOADED = 'PURCHASE_RETURN_LOADED';
export const CLEAR_PURCHASE_RETURN = 'CLEAR_PURCHASE_RETURN';
export const FILTER_PURCHASE_TYPE = 'FILTER_PURCHASE_TYPE';
export const CLEAR_FILTER_TYPE = 'CLEAR_FILTER_TYPE';

/* BLOG */
export const ADD_BLOG = 'ADD_BLOG';
export const BLOG_ERROR = 'BLOG_ERROR';
export const GET_BLOGS = 'GET_BLOGS';
export const FILTER_BLOGS = 'FILTER_BLOGS';
export const UPDATE_BLOG = 'UPDATE_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
export const UPDATE_FILTER_DATA = 'UPDATE_FILTER_DATA';
export const ADD_BLOG_CATEGORY = 'ADD_BLOG_CATEGORY';
export const DELETE_BLOG_CATEGORY = 'DELETE_BLOG_CATEGORY';
export const FILTER_CATEGORYS = 'FILTER_CATEGORYS';
export const CLEAR_CATEGORY_FILTER = 'CLEAR_CATEGORY_FILTER';

/* Purchase REPORT */
export const PURCHASE_REPORT_LOADED = 'PURCHASE_REPORT_LOADED';
export const PURCHASE_REPORT_ERROR = 'PURCHASE_REPORT_ERROR';
export const PURCHASE_REPORT_NULL = 'PURCHASE_REPORT_NULL';
export const PURCHASE_RETURN_REPORT_LOADED = 'PURCHASE_RETURN_REPORT_LOADED';
export const PURCHASE_RETURN_REPORT_ERROR = 'PURCHASE_RETURN_REPORT_ERROR';
export const PURCHASE_RETURN_REPORT_NULL = 'PURCHASE_RETURN_REPORT_NULL';
export const FILTER_PURCHASE_RETURN = 'FILTER_PURCHASE_RETURN';
export const FILTER_PURCHASE_REPORT = 'FILTER_PURCHASE_REPORT';

// Sales Reports

export const GET_SALES = 'GET_SALES';
export const SALES_ERROR = 'SALES_ERROR';
export const GET_SALES_NULL = 'GET_SALES_NULL';
export const GET_AMOUNTS = 'GET_AMOUNTS';

//SALES RETURN REPORTS
export const GET_SALES_RETURN = 'GET_SALES_RETURN';
export const SALES_RETURN_ERROR = 'SALES_RETURN_ERROR';
export const SALES_RETURN_NULL = 'GET_SALES_NULL';
export const FILTER_SALES = 'FILTER_SALES';
export const FILTER_SALES_RETURN = 'FILTER_SALES_RETURN';

//PRODUCT REPORTS
export const PRODUCT_REPORT_LOADED = 'PRODUCT_REPORT_LOADED';
export const PRODUCT_REPORT_ERROR = 'PRODUCT_REPORT_ERROR';
export const PRODUCT_REPORT_NULL = 'PRODUCT_REPORT_NULL';
export const FILTER_PRODUCT_REPORT = 'FILTER_PRODUCT_REPORT';

//DASHBOARD
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const SET_DASHBOARD_LOADING = 'SET_DASHBOARD_LOADING';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const CLEAR_DASHBOARD_SCHOOLS_FILTER = 'CLEAR_DASHBOARD_SCHOOLS_FILTER';
export const FILTER_DASHBOARD_SCHOOLS = 'FILTER_DASHBOARD_SCHOOLS';
export const CLEAR_DASHBOARD_CITY_FILTER = 'CLEAR_DASHBOARD_CITY_FILTER';
export const FILTER_DASHBOARD_CITIES = 'FILTER_DASHBOARD_CITIES';
export const FILTER_DASHBOARD_COUNTRIES = 'FILTER_DASHBOARD_COUNTRIES';
export const CLEAR_DASHBOARD_COUNTRIES_FILTER =
  'CLEAR_DASHBOARD_COUNTRIES_FILTER';
export const GET_CITY_NAME = 'GET_CITY_NAME';
export const CLEAR_DASHBOARD_ERRORS = 'CLEAR_DASHBOARD_ERRORS';
export const CLEAR_DASHBOARD_MESSAGE = 'CLEAR_DASHBOARD_MESSAGE';

//ORDERS
export const ORDERS_LOADED = 'ORDERS_LOADED';
export const ORDER_DETAILS = 'ORDER_DETAILS';
export const FILTER_ORDERS = 'FILTER_ORDERS';
export const APPROVE_ORDER = 'APPROVE_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';
export const APPROVE_ERROR = 'APPROVE_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const NOTIFIC_ORDERS_LOADED = 'NOTIFIC_ORDERS_LOADED';

//USER MAGAGEMENT
export const SET_SUB_ADMIN_LOADING = 'SET_SUB_ADMIN_LOADING';
export const CLEAR_SUB_ADMIN_ERRORS = 'CLEAR_SUB_ADMIN_ERRORS';
export const CLEAR_SUB_ADMIN_MESSAGE = 'CLEAR_SUB_ADMIN_MESSAGE';
export const GET_ADMIN_DATA = 'GET_ADMIN_DATA';
export const ADMIN_DATA_ERROR = 'ADMIN_DATA_ERROR';
export const ALLOW_ACCESS = 'ALLOW_ACCESS';

export const GET_SUB_ADMIN = 'GET_SUB_ADMIN';
export const SUB_ADMIN_ERROR = 'SUB_ADMIN_ERROR';
export const ADD_SUB_ADMIN = 'ADD_SUB_ADMIN';
export const UPDATE_SUB_ADMIN = 'UPDATE_SUB_ADMIN';
export const DELETE_SUB_ADMIN = 'DELETE_SUB_ADMIN';
export const ASSIGN_ROLE = 'ASSIGN_ROLE';
export const ASSIGN_ROLE_ERROR = 'ASSIGN_ROLE_ERROR';
export const GET_USER_ROLES = 'GET_USER_ROLES';
export const USER_ROLES_ERROR = 'USER_ROLES_ERROR';
export const FILTER_USERS = 'FILTER_USERS';
export const CLEAR_USER_FILTER = 'CLEAR_USER_FILTER';

//EMAIL TEMPLATES
export const GET_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';
export const EMAIL_TEMPLATES_ERROR = 'EMAIL_TEMPLATES_ERROR';
export const GET_EMAIL_DETAILS = 'GET_EMAIL_DETAILS';
export const EMAIL_DETAILS_ERROR = 'EMAIL_DETAILS_ERROR';
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const UPDATE_TEMPLATE_ERROR = 'UPDATE_TEMPLATE_ERROR';

//SCHOOLS
export const GET_SCHOOLS = 'GET_SCHOOLS';
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const SCHOOL_ERROR = 'SCHOOL_ERROR';
export const FILTER_SCHOOLS = 'FILTER_SCHOOLS';
export const CLEAR_SCHOOLS_FILTER = 'CLEAR_SCHOOLS_FILTER';
export const SET_SCHOOL_LOADING = 'SET_SCHOOL_LOADING';
export const CLEAR_SCHOOL_ERRORS = 'CLEAR_SCHOOL_ERRORS';
export const CLEAR_SCHOOL_MESSAGE = 'CLEAR_SCHOOL_MESSAGE';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const VIEW_SCHOOL = 'VIEW_SCHOOL';
export const CLEAR_SCHOOLS_ID = 'CLEAR_SCHOOLS_ID';
export const GET_SUBSCRIPTION_HISTORY = 'GET_SUBSCRIPTION_HISTORY';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const COUNTRIES_ERROR = 'COUNTRIES_ERROR';
export const GET_STATES = 'GET_STATES';
export const STATES_ERROR = 'STATES_ERROR';
export const GET_CITIES = 'GET_CITIES';
export const CITIES_ERROR = 'CITIES_ERROR';

//PACKAGE
export const GET_PACKAGES = 'GET_PACKAGES';
export const ADD_PACKAGE = 'ADD_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const PACKAGE_ERROR = 'PACKAGE_ERROR';
export const FILTER_PACKAGE = 'FILTER_PACKAGE';
export const CLEAR_PACKAGE_FILTER = 'CLEAR_PACKAGE_FILTER';
export const SET_PACKAGE_LOADING = 'SET_PACKAGE_LOADING';
export const CLEAR_PACKAGE_ERRORS = 'CLEAR_PACKAGE_ERRORS';
export const CLEAR_PACKAGE_MESSAGE = 'CLEAR_PACKAGE_MESSAGE';
export const GET_PACKAGE_ID = 'GET_PACKAGE_ID';
export const PACKAGE_DETAILS = 'PACKAGE_DETAILS';
export const CLEAR_PACKAGE_ID = 'CLEAR_PACKAGE_ID';

//QUERIES
export const GET_QUERIES = 'GET_QUERIES';
export const QUERIES_REPLY = 'QUERIES_REPLY';
export const QUERY_ERROR = 'QUERY_ERROR';
export const FILTER_QUERIES = 'FILTER_QUERIES';
export const CLEAR_QUERIES_FILTER = 'CLEAR_QUERIES_FILTER';
export const SET_QUERY_LOADING = 'SET_QUERY_LOADING';
export const CLEAR_QUERY_ERRORS = 'CLEAR_QUERY_ERRORS';
export const CLEAR_QUERY_MESSAGE = 'CLEAR_QUERY_MESSAGE';
export const DELETE_QUERY = 'DELETE_QUERY';

//CLASS
export const GET_CLASSES = 'GET_CLASSES';
export const ADD_CLASS = 'ADD_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
export const FILTER_CLASSES = 'FILTER_CLASSES';
export const SET_CLASS_LOADING = 'SET_CLASS_LOADING';
export const CLASS_ERROR = 'CLASS_ERROR';
export const CLEAR_CLASSES_FILTER = 'CLEAR_CLASSES_FILTER';
export const CLEAR_CLASS_ERRORS = 'CLEAR_CLASS_ERRORS';
export const CLEAR_CLASS_MESSAGE = 'CLEAR_CLASS_MESSAGE';

//ROLE
export const GET_ROLES = 'GET_ROLES';
export const ADD_ROLE = 'ADD_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const FILTER_ROLES = 'FILTER_ROLES';
export const SET_ROLE_LOADING = 'SET_ROLE_LOADING';
export const ROLE_ERROR = 'ROLE_ERROR';
export const CLEAR_ROLES_FILTER = 'CLEAR_ROLES_FILTER';
export const CLEAR_ROLE_MESSAGE = 'CLEAR_ROLE_MESSAGE';
export const CLEAR_ROLE_ERRORS = 'CLEAR_ROLE_ERRORS';

//SALES PERSONS
export const GET_SALES_PERSONS = 'GET_SALES_PERSONS';
export const ADD_SALES_PERSONS = 'ADD_SALES_PERSONS';
export const UPDATE_SALES_PERSONS = 'UPDATE_SALES_PERSONS';
export const FILTER_SALES_PERSONS = 'FILTER_SALES_PERSONS';
export const SET_SALES_PERSONS_LOADING = 'SET_SALES_PERSONS_LOADING';
export const SALES_PERSONS_ERROR = 'SALES_PERSONS_ERROR';
export const CLEAR_SALES_PERSONS_FILTER = 'CLEAR_SALES_PERSONS_FILTER';
export const CLEAR_SALES_PERSONS_MESSAGE = 'CLEAR_SALES_PERSONS_MESSAGE';
export const CLEAR_SALES_PERSONS_ERRORS = 'CLEAR_SALES_PERSONS_ERRORS';
//RENEWABLE_REQUEST
export const GET_RENEWABLE_REQUEST = 'GET_RENEWABLE_REQUEST';
export const ADD_RENEWABLE_REQUEST = 'ADD_RENEWABLE_REQUEST';
export const UPDATE_RENEWABLE_REQUEST = 'UPDATE_RENEWABLE_REQUEST';
export const RENEWABLE_REQUEST_ERROR = 'RENEWABLE_REQUEST_ERROR';
export const FILTER_RENEWABLE_REQUEST = 'FILTER_RENEWABLE_REQUEST';
export const CLEAR_RENEWABLE_REQUEST_FILTER = 'CLEAR_RENEWABLE_REQUEST_FILTER';
export const SET_RENEWABLE_REQUEST_LOADING = 'SET_RENEWABLE_REQUEST_LOADING';
export const CLEAR_RENEWABLE_REQUEST_ERRORS = 'CLEAR_RENEWABLE_REQUEST_ERRORS';
export const CLEAR_RENEWABLE_REQUEST_MESSAGE =
  'CLEAR_RENEWABLE_REQUEST_MESSAGE';

// Income
export const GET_INCOME = 'GET_INCOME';
export const INCOME_ERROR = 'INCOME_ERROR';
export const FILTER_INCOME = 'FILTER_INCOME';
export const CLEAR_INCOME_FILTER = 'CLEAR_INCOME_FILTER';
export const SET_INCOME_LOADING = 'SET_INCOME_LOADING';
export const CLEAR_INCOME_ERRORS = 'CLEAR_INCOME_ERRORS';
export const CLEAR_INCOME_MESSAGE = 'CLEAR_INCOME_MESSAGE';
export const INCOME_DETAILS = 'INCOME_DETAILS';
export const CLEAR_INCOME_PACKAGE_ID = 'CLEAR_INCOME_PACKAGE_ID';
export const ADD_SUB = 'ADD_SUB';

// Support
export const SUPPORT_SEND = 'SUPPORT_SEND';
export const SUPPORT_ERROR = 'SUPPORT_ERROR';
export const SUPPORT_LOADING = 'SUPPORT_LOADING';
export const SUPPORT_CLEAR_MESSAGE = 'SUPPORT_CLEAR_MESSAGE';
export const SUPPORT_CLEAR_ERROR = 'SUPPORT_CLEAR_ERROR';

// Notification
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const SET_NOTIFICATION_LOADING = 'SET_NOTIFICATION_LOADING';
export const CLEAR_NOTIFICATION_ERRORS = 'CLEAR_NOTIFICATION_ERRORS';
export const CLEAR_NOTIFICATION_MESSAGE = 'CLEAR_NOTIFICATION_MESSAGE';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';

// City_Schools
export const GET_CITY_SCHOOLS = 'GET_CITY_SCHOOLS';
export const CITY_SCHOOLS_ERROR = 'CITY_SCHOOLS_ERROR';
export const FILTER_CITY_SCHOOLS = 'FILTER_CITY_SCHOOLS';
export const CLEAR_CITY_SCHOOLS_FILTER = 'CLEAR_CITY_SCHOOLS_FILTER';
export const SET_CITY_SCHOOLS_LOADING = 'SET_CITY_SCHOOLS_LOADING';
export const CLEAR_CITY_SCHOOLS_ERRORS = 'CLEAR_CITY_SCHOOLS_ERRORS';
export const CLEAR_CITY_SCHOOLS_MESSAGE = 'CLEAR_CITY_SCHOOLS_MESSAGE';

// Section

export const CLEAR_SECTION_ERRORS = 'CLEAR_SECTION_ERRORS';
export const SET_SECTION_LOADING = 'SET_SECTION_LOADING';
export const CLEAR_SECTION_MESSAGE = 'CLEAR_SECTION_MESSAGE';
export const ADD_SECTION = 'ADD_SECTION';
export const SECTION_ERROR = 'SECTION_ERROR';
export const GET_SECTIONS = 'GET_SECTIONS';
export const UPDATE_SECTION = 'UPDATE_SECTION';
export const FILTER_SECTIONS = 'FILTER_SECTIONS';
export const CLEAR_SECTION_FILTER = 'CLEAR_SECTION_FILTER';
export const GET_CLASS_SECTIONS = 'GET_CLASS_SECTIONS';

// Fee Group

export const CLEAR_FEE_GROUP_ERRORS = 'CLEAR_FEE_GROUP_ERRORS';
export const SET_FEE_GROUP_LOADING = 'SET_FEE_GROUP_LOADING';
export const CLEAR_FEE_GROUP_MESSAGE = 'CLEAR_FEE_GROUP_MESSAGE';
export const ADD_FEE_GROUP = 'ADD_FEE_GROUP';
export const FEE_GROUP_ERROR = 'FEE_GROUP_ERROR';
export const GET_FEE_GROUPS = 'GET_FEE_GROUPS';
export const FILTER_FEE_GROUPS = 'FILTER_FEE_GROUPS';
export const UPDATE_FEE_GROUP = 'UPDATE_FEE_GROUP';
export const CLEAR_FEE_GROUP_FILTER = 'CLEAR_FEE_GROUP_FILTER';

// Fee Type

export const CLEAR_FEE_TYPE_ERRORS = 'CLEAR_FEE_TYPE_ERRORS';
export const SET_FEE_TYPE_LOADING = 'SET_FEE_TYPE_LOADING';
export const CLEAR_FEE_TYPE_MESSAGE = 'CLEAR_FEE_TYPE_MESSAGE';
export const ADD_FEE_TYPE = 'ADD_FEE_TYPE';
export const FEE_TYPE_ERROR = 'FEE_TYPE_ERROR';
export const GET_FEE_TYPES = 'GET_FEE_TYPES';
export const UPDATE_FEE_TYPE = 'UPDATE_FEE_TYPE';
export const FILTER_FEE_TYPES = 'FILTER_FEE_TYPES';
export const CLEAR_FEE_TYPE_FILTER = 'CLEAR_FEE_TYPE_FILTER';

// Fee Discount

export const CLEAR_FEE_DISCOUNT_ERRORS = 'CLEAR_FEE_DISCOUNT_ERRORS';
export const SET_FEE_DISCOUNT_LOADING = 'SET_FEE_DISCOUNT_LOADING';
export const CLEAR_FEE_DISCOUNT_MESSAGE = 'CLEAR_FEE_TYPE_MESSAGE';
export const ADD_FEE_DISCOUNT = 'ADD_FEE_DISCOUNT';
export const FEE_DISCOUNT_ERROR = 'FEE_DISCOUNT_ERROR';
export const GET_FEE_DISCOUNT = 'GET_FEE_DISCOUNT';
export const UPDATE_FEE_DISCOUNT = 'UPDATE_FEE_DISCOUNT';
export const FILTER_FEE_DISCOUNT = 'FILTER_FEE_DISCOUNT';
export const CLEAR_FEE_DISCOUNT_FILTER = 'CLEAR_FEE_DISCOUNT_FILTER';

// Student Category

export const CLEAR_STUD_CAT_ERRORS = 'CLEAR_STUD_CAT_ERRORS';
export const SET_STUD_CAT_LOADING = 'SET_STUD_CAT_LOADING';
export const CLEAR_STUD_CAT_MESSAGE = 'CLEAR_FEE_TYPE_MESSAGE';
export const ADD_STUD_CAT = 'ADD_STUD_CAT';
export const STUD_CAT_ERROR = 'STUD_CAT_ERROR';
export const GET_STUD_CAT = 'GET_STUD_CAT';
export const UPDATE_STUD_CAT = 'UPDATE_STUD_CAT';
export const FILTER_STUD_CAT = 'FILTER_STUD_CAT';
export const CLEAR_STUD_CAT_FILTER = 'CLEAR_STUD_CAT_FILTER';

// Email/SMS Log
export const CLEAR_EMAIL_LOG_ERRORS = 'CLEAR_EMAIL_LOG_ERRORS';
export const SET_EMAIL_LOG_LOADING = 'SET_EMAIL_LOG_LOADING';
export const CLEAR_EMAIL_LOG_MESSAGE = 'CLEAR_EMAIL_LOG_MESSAGE';
export const ADD_EMAIL_LOG = 'ADD_EMAIL_LOG';
export const EMAIL_LOG_ERROR = 'EMAIL_LOG_ERROR';
export const GET_EMAIL_LOGS = 'GET_EMAIL_LOGS';
export const UPDATE_EMAIL_LOG = 'UPDATE_EMAIL_LOG';
export const FILTER_EMAIL_LOGS = 'FILTER_EMAIL_LOGS';
export const CLEAR_EMAIL_LOG_FILTER = 'CLEAR_EMAIL_LOG_FILTER';

// Assign Section

export const CLEAR_ASSIGN_SECTION_ERRORS = 'CLEAR_ASSIGN_SECTION_ERRORS';
export const SET_ASSIGN_SECTION_LOADING = 'SET_ASSIGN_SECTION_LOADING';
export const CLEAR_ASSIGN_SECTION_MESSAGE = 'CLEAR_ASSIGN_SECTION_MESSAGE';
export const ADD_ASSIGN_SECTION = 'ADD_ASSIGN_SECTION';
export const ASSIGN_SECTION_ERROR = 'ASSIGN_SECTION_ERROR';
export const GET_ASSIGN_SECTIONS = 'GET_ASSIGN_SECTIONS';
export const UPDATE_ASSIGN_SECTION = 'UPDATE_ASSIGN_SECTION';
export const FILTER_ASSIGN_SECTIONS = 'FILTER_ASSIGN_SECTIONS';
export const CLEAR_ASSIGN_SECTION_FILTER = 'CLEAR_ASSIGN_SECTION_FILTER';

// Fee Master
export const CLEAR_FEE_MASTER_ERRORS = 'CLEAR_FEE_MASTER_ERRORS';
export const SET_FEE_MASTER_LOADING = 'SET_FEE_MASTER_LOADING';
export const CLEAR_FEE_MASTER_MESSAGE = 'CLEAR_FEE_MASTER_MESSAGE';
export const ADD_FEE_MASTER = 'ADD_FEE_MASTER';
export const FEE_MASTER_ERROR = 'FEE_MASTER_ERROR';
export const GET_FEE_MASTER = 'GET_FEE_MASTER';
export const UPDATE_FEE_MASTER = 'UPDATE_FEE_MASTER';
export const FILTER_FEE_MASTER = 'FILTER_FEE_MASTER';
export const CLEAR_FEE_MASTER_FILTER = 'CLEAR_FEE_MASTER_FILTER';
